pettify/pettify/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Examples:
    # url(r'^$', 'pettify.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^pettify/', include('pettifyapp.urls')),
    url(r'^admin/', include(admin.site.urls)),   
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pettify/pettifyapp/urls.py
from django.conf.urls import url

from . import views
from .models import Animal

app_name = 'pettifyapp'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^animals/$', views.listing, name='listing'),
	url(r'^animals/category/$', views.category, name='category'),
	url(r'^animals/(?P<id>[0-9]+)/$', views.result, name='result'),
]

pettify/pettifyapp/models.py
from django.db import models

import datetime
from django.utils import timezone


# Create your models here.
class Selector(models.Model):
	category = models.CharField(max_length=60)	
	def __unicode__(self):
		return self.category
	def __str__(self):
		return self.category

class House(models.Model):
	home = models.CharField(max_length=60)	
	phone = models.CharField(max_length=60)	
	def __unicode__(self):
		return self.home
	def __str__(self):
		return self.home

		

class Animal(models.Model):
	animal_name = models.CharField(max_length=60)
	Male = 'Male'
	Female = 'Female'
	none = ''
	gender_choices = (
		('none', none),
		('Male', Male),
		('Female', Female),
	)
	image = models.FileField(null=True, blank=True)
	category = models.ForeignKey('Selector', on_delete=models.CASCADE)
	shelter = models.ForeignKey('House', on_delete=models.CASCADE)
	age = models.IntegerField(default=0)
	gender = models.CharField(default=none, choices=gender_choices, max_length=6)
	updated = models.DateTimeField(auto_now=False,auto_now_add=True)
	timestamp = models.DateTimeField(auto_now=True,auto_now_add=False)
	
	
	def __unicode__(self):
		return self.animal_name
	def __str__(self):
		return self.animal_name

	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

pettify/pettifyapp/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import HttpResponse
from .models import Animal

# Create your views here.
def index(request):
    return render(request, 'pettifyapp/index.html')

def listing(request):
	newest_animals_list = Animal.objects.order_by('category')
	# order_by('pub_date')[:5]
	template = loader.get_template('pettifyapp/animals.html')
	context = {
		'newest_animals_list': newest_animals_list
	}
	return render(request, 'pettifyapp/animals.html', context)

def category(request):
	return render(request, 'pettifyapp/category.html')

def result(request, id):
	animal = get_object_or_404(Animal, pk=id)
	return render(request, 'pettifyapp/one.html', {'animal': animal})

pettify/pettifyapp/templates/pettifyapp/animals.html
{% extends "base.html" %}

{% block content %}
<!-- Type html stuff here -->
<!-- Don't use <html>, <body>, <head> -->
{% if newest_animals_list %}
    {% for all_animals in newest_animals_list %}
    <h3><a href="{% url 'pettifyapp:category' %}">{{ all_animals.category }}</a></h3>
    {{ all_animals.animal_name }}
    
    <img src="{{ all_animals.image.url }}">
    
    {% endfor %}
{% else %}
    <p>No animals_list are available.</p>
{% endif %}
{% endblock content %}

pettify/pettifyapp/templates/pettifyapp/category.html
{% extends "base.html" %}

{% block content %}
<!-- Type html stuff here -->
<!-- Don't use <html>, <body>, <head> -->
{% if category_list %}
    {% for all_animals in category_list %}
    <h3>{{ all_animals.category }}</h3>
    {{ all_animals.name }}
    
    {% endfor %}
{% else %}
    <p>No list are available.</p>
{% endif %}
{% endblock content %}

pettify/pettifyapp/templates/pettifyapp/index.html
{% extends "base.html" %}

{% block content %}
<!-- Type html stuff here -->
<!-- Don't use <html>, <body>, <head> -->
<h1>fiwfjiofw</h1>

{% endblock content %}

pettify/pettifyapp/templates/pettifyapp/one.html
{% extends "base.html" %}

{% block content %}
<!-- Type html stuff here -->
<!-- Don't use <html>, <body>, <head> -->
<h1>{{ animal.name }}</h1>
<img src="{{ animal.image.url }}">
<p>Category: {{ animal.category }}</p>
<p>Shelter: {{ animal.shelter }}</p>
<p>Age: {{ animal.age }}</p>
<p>Gender: {{ animal.gender }}</p>
{% endblock content %}

pettify/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
	<head>
	<title>
		{% block head_title %} 
		Pettify
		{% endblock head_title %}
	</title>
	<!-- Foundation css -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/foundation/6.1.2/foundation.min.css">
	<!-- App css -->
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
	</head>
	<body>

		<div class="container">
			{% block content %}
			{% endblock content%}
		</div>
		<!-- Jquery js -->
		<script src="http://code.jquery.com/jquery-2.2.0.min.js"></script>
		<!-- Foundation js -->
		<script src="https://cdn.jsdelivr.net/foundation/6.1.2/foundation.min.js"></script>
	</body>
</html>

pettify/templates/index.html
{% extends "base.html" %}

{% block content %}
<!-- Type html stuff here -->
<!-- Don't use <html>, <body>, <head> -->

{% endblock content %}